# Setup
title:        Tavi
tagline:      A simple iOS app for Travis-CI
baseurl:      "/Tavi"
projecturl:   https://github.com/thislooksfun/Tavi
producturl:   "" #TODO: Make this link to the App Store once it is uploaded, and add button on main page and in menu

# Pagenation
paginate:      5
paginate_path: "/blog/page/:num/"

# Author
author:
  name: thislooksfun
  url:  https://github.com/thislooksfun

# About/contact
contact:
  twitter:
    username: "@thislooksfun1"
    url: https://twitter.com/thislooksfun1
  github:
    username: thislooksfun
    url: https://github.com/thislooksfun

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet